Updated map page
UNLV-CS472-672/2024-S-GROUP6-RW pull request #85
Opened 2024-03-26 22:36 UTC by printer99

---
name: "Map Page Improvements"
about: "Request a feature"
title: "feat: "
labels: "feature-request, not-reviewed"
assignees: ""
---

# Description

- Originally the map page was using a map block per image and I have consolidated that to use the same map block per category.
- I have added a few more images to the popular trips part as an example of how it will function
- The names of locations was added to the bottom left corner of each image
- Currently the map appears below the entire section when any image is clicked in Popular trips that will be changed to instead appear below the image clicked in the future.
- Currently the images that wrap around to the next line are centered, however if someone thinks it would look better if they were on the left side I can try to change that in a future PR.
- Code will be a substantially shorter now due to the use of less map blocks 

Fixes # (issue)

# Add an image of the change (if applicable)

# Type of change

- [ ] Bug fix 
- [ ] New feature 
- [ ] Breaking change 
- [ ] This change requires a documentation update

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-03-26 23:09 UTC, axelauda requested changes
This is a good improvement to the map page, and now there's more space since there is only one map displaying instead of opening a new map for every trip clicked. Nice work refactoring and shortening the code too! You did install an external library however with "react-responsive-carousel", so just make sure that this is added to package.json. You can do this by going into your local repository, typing "cd frontend", and then typing "npm install react-responsive-carousel --save". This will save this to your package.json file, and then you can push it and merge it with the master's package.json. After you push this, I'll approve!

2024-03-27 00:13 UTC, printer99 commented
Carousel lines that were  unused have been removed

2024-03-27 00:47 UTC, axelauda approved these changes

2024-03-27 00:49 UTC, Jordan-Scherf approved these changes
Great Job, The map page is starting to look amazing. Currently we are having issues with the package.json as it is not bringing in the dependencies needed for the program, however this is currently being fixed in master which will be be done soon. This is good to merge.

2024-03-27 00:49 UTC, merged